### ISSUE TITLE
not able to run the website locally

### ISSUE THREAD

**Issue by thescientist13** [wintercg/www#37]
Was trying to follow the steps in the _README_ to run the site locally, and experienced this issue
```sh
➜  www git:(main) deno run -A --no-check main.jsx
error: The source code is invalid, as it does not match the expected hash in the lock file.
  Specifier: https://esm.sh/*@twind/typography@0.0.2
  Lock file: /Users/owenbuckley/Workspace/github/wintercg/www/deno.lock
```

Can confirm that **deno** is installed locally
```sh
➜  www git:(main) deno --version
deno 1.38.0 (release, aarch64-apple-darwin)
v8 12.0.267.1
typescript 5.2.2
```

Any thoughts?  I'm new to deno, so not sure if it is just user error or something else 😅

**Comment by lucacasonato** [comment]
Try `rm deno.lock`?

**Comment by thescientist13** [comment]
So in doing that, the server started, but then failed to render the page (presumably because there is no lock file anymore?)
```sh
✗ deno run -A --no-check main.jsx
Listening on http://localhost:8000
ReferenceError: h is not defined
    at file:///Users/owenbuckley/Workspace/github/wintercg/www/main.jsx:458:22
    at ssr (https://crux.land/api/get/7GrKMy.ts:55:26)
    at Server.<anonymous> (file:///Users/owenbuckley/Workspace/github/wintercg/www/main.jsx:458:12)
    at Server.#respond (https://deno.land/std@0.135.0/http/server.ts:298:37)
    at Server.#serveHttp (https://deno.land/std@0.135.0/http/server.ts:340:20)
    at eventLoopTick (ext:core/01_core.js:183:11)
```

<img width="990" alt="Screenshot 2023-11-02 at 12 07 07 PM" src="https://github.com/wintercg/www/assets/895923/0283d8bd-6bcd-4d8a-8e26-2abb04fded77">

**Comment by thescientist13** [comment]
So I tried the following again and got the site working!
1. Re-run the deno installer script
1. Run the `deno` command to start the site (got the same lock file error)
1. Remove the _deno.lock_ file
1. Run the deno command to start the site (now it works!)

So now I have a diff on _deno.lock_, should I open a PR with those updated contents?
```sh
➜  www git:(main) ✗ git status
On branch main
Your branch is up to date with 'origin/main'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   deno.lock

no changes added to commit (use "git add" and/or "git commit -a")
```

**Comment by thescientist13** [comment]
closing now that #40 has been merged.
