### ISSUE TITLE
Add more logos

### ISSUE THREAD

**Issue by lucacasonato** [wintercg/www#9]
I'd be great if we could add more parter logos.

We currently have a Cloudflare and a Deno logo.

Considering we have members from all of these companies too, do they want to add their logos?

- Bloomberg: @wintercg/members-bloomberg 
- Igalia: @wintercg/members-igalia
- Shopify: @wintercg/members-shopify
- Vercel: @wintercg/members-vercel 

If so, please open a PR to add your logo [here](https://github.com/wintercg/www/blob/02815f0ea314d249c67bde5f03a65a59edb9938f/main.jsx#L330).

**Comment by XadillaX** [comment]
I've created a PR for ByteDance

**Comment by thescientist13** [comment]
All these logos are now on the public site, so perhaps this one can be closed down?
https://wintercg.org/
![Screenshot 2024-01-04 at 10 59 47 AM](https://github.com/wintercg/www/assets/895923/be12b7c4-b32b-4364-80af-bb0fee01e185)
